version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: SyncSipDb
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: SyncSipDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lol123
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
